### PR TITLE
Fix arbitrary file reading vulnerabilities.

### PR DESCRIPTION
**Pull request by haby0**
Use `werkzeug.utils.secure_filename` to fix arbitrary file reading vulnerabilities.

### CODE REVIEW

**Comment by haby0** [comment]
From: https://github.com/google/shaka-streamer/issues/102

**Review by joeyparrish — APPROVED** [review]
Thank you!

**Comment by joeyparrish** [comment]
@haby0, can you please look at https://github.com/google/shaka-streamer/pull/104/checks?check_run_id=4501299635 and sign the CLA?

**Comment by haby0** [comment]
@joeyparrish I have signed the CLA.

**Pull request merged**
