### PR TITLE
Add support for ac3 and ec3 #37

### PR DESCRIPTION
**Pull request by ans-negi**

### CODE REVIEW

**Comment by ans-negi** [comment]
#37

**Comment by ans-negi** [comment]
@googlebot I signed it!

**Comment by joeyparrish** [comment]
This looks good to me, but I have one question: On what did you base the bitrate choices for ac3 and ec3?

**Comment by ans-negi** [comment]
@joeyparrish Hey they were recommended bitrates at [FFmpeg site ](https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio), so from there I took stereo values. 
And I realised for Opus and aac there was a relation between stereo and surround values, so to calculate for surround value for ac-3 and ec-3 I used same formula (160)*(6)/2*2 == 240k

**Comment by avelad** [comment]
I would like more to take the values that Apple gives for Reference in HLS.
https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices

image

What do you think?

**Comment by joeyparrish** [comment]
@avelad, how about this: We adjust the defaults to be more similar to Apple's recommendations, and we also create a explicit bitrate config file that exactly matches what Apple suggests, including for video.

Here's a compromise between our existing values (extrapolated from Google internal recommendations) and Apple's recommendations:

Num. Channels | AAC Bitrate | Opus Bitrate | AC3 Bitrate | EAC3 Bitrate
-- | -- | -- | -- | --
2 | 128 | 64 | 192 | 96
6 | 256 | 128 | 384 | 192

@avelad, @ans-negi, if y'all both agree, let's use the value above as the default.

**Comment by avelad** [comment]
I agree!

**Review by joeyparrish — APPROVED** [review]

**Comment by joeyparrish** [comment]
Thanks for your contribution!

**Pull request merged**
